export const pashto = {
  No_active_account_found: 'کارن نوم او یا رمز غلط دی',
  error: 'سرور کې تېروتنه',
  dashboard: 'ډشبورډ',
  mujtaba: 'مجتبی',

  id: 'ID',
  name: 'نوم',
  full_name: 'بشپړ نوم',
  father_name: 'پلار نوم',
  g_father_name: 'پلار پلار نوم',
  gender: 'جنس',
  birth_date: 'زېږون نېټه',
  birth_place: 'زېږون ځای',
  district: 'ولسوالۍ',
  province: 'ولايت',
  email: 'برېښليک',
  identification_number: 'کارت شمېره',
  profile_image: 'پروفايل انځور',
  created_at: 'نېټه جوړ شو',
  updated_at: 'نېټه تازه شو',
  'direct permissions list': 'مستقيم اجازې لړليک',
  'roles list': 'رولونه لړليک',
  'permissions by roles': 'رولونو لخوا اجازې',
  'English Full Name': 'انګليسي بشپړ نوم',
  Name: 'نوم',

  'Father Name': 'پلار نوم',
  'G-Father Name': 'پلار پلار نوم',
  Gender: 'جنس',
  Email: 'برېښليک',
  'Birth Date': 'زېږون نېټه',
  'Birth Place': 'زېږون ځای',
  Province: 'ولايت',
  District: 'ولسوالۍ',
  'Card ID#': 'کارت شمېره',
  Password: 'رمز',
  'Re Password': 'رمز بيا وليکه',
  Department: 'رياست',
  Permission: 'اجازه',
  Role: 'رول',
  Save: 'ثبت',
  Cancel: 'لغوه کول',
  'New User': 'نوی کارن',
  'This field should be string': 'دا سيمه بايد رشته وي',
  'This field can not be empty': 'دا سيمه نشي تش وي',
  'This field can not be less than 4 chracters': 'دا سيمه نشي له 4 حروفو څخه لږ وي',
  'This field can not be less than 3 chracters': 'دا سيمه نشي له 3 حروفو څخه لږ وي',
  'This field can not be less than 10 chracters': 'دا سيمه نشي له 10 حروفو څخه لږ وي',

  'Must Contain 8 Characters, One Uppercase, One Lowercase, One Number and One Special Case Character':
    'رمز باید 8 وي: لوی حرف، کښنی حرف، شمېره او ځانګړي حروف مانند !@#$',

  're password not match': 'رمز بيا وليکل سم نه دی',

  'Not a valid image type': 'انځور ډول سم نه دی',

  'Old Password': 'زوړ رمز',
  'New Password': 'نوی رمز',
  'Re New Password': 'نوی رمز بيا وليکه',
  'Re Password': 'رمز بيا وليکه',
  'Update User': 'کارن تازه کول',
  New: 'نوی',
  ID: '#',
  Action: 'عمل',
  'Guard Name': 'API نوم',
  'Are you sure?': 'آيا ډاډه ياست؟',
  "You won't be able to revert this!": 'تاسو نشئ ترته برگرځولی!',
  'Yes, delete it!': 'هو، ړنګول',
  Gender: 'جنس',
  'Personel Information': 'شخصي مالومات',
  'Tazkira Information': 'تذکره مالومات',
  'Birth and Currenet Place': 'سکونت',
  'Enroll Information': 'استخدام مالومات',
  'Other Information': 'نور مالومات',
  Next: 'راتلونکی',
  Paper: 'کاغذي',
  Electronic: 'الکترونيکي',
  identifecation_type: 'تذکره ډول',
  identifecation_number: 'تذکره الکترونيکي شمېره',
  'Paper id number': 'تذکره شمېره',
  Book: 'جلد',
  Page: 'صفحه',
  'Sokok Number': 'صکوک شمېره',
  'Current Live Place': 'قريه',
  'Born Place Information': 'اصلي سکونت',
  'Current Live Information': 'اوسنۍ سکونت',
  Back: 'شاته',
  'Enroll Type': 'استخدام ډول',
  Bast: 'بست',
  Stip: 'قدم',
  Rotba: 'رتبه',
  Grade: 'ګريډ',

  Contractual: 'قراردادي',
  'Salary Amount': 'معاش مقدار',
  Bank: 'بانک',
  'Account Name': 'بانکي حساب نوم',
  'Account Number': 'بانکي حساب شمېره',
  'Bank Account': 'بانکي حساب',
  'Assign Permissions': 'اجازه ورکول',
  'Card ID Number': 'کارت شمېره',
  'Initail Date': 'بست تعيين نېټه',
  'Fastening Determination': 'ثبت نېټه',
  'Register Number': 'ثبت شمېره',
  'Start Date': 'پيل نېټه',
  'End Date': 'پای نېټه',
  'Main Place': 'اصلي سکونت',
  Village: 'قريه',
  'Last Name': 'تخلص',
  'Save Information': 'مالومات ثبت کول',
  'Stablization of Rank Date': 'رتبه ثبت نېټه',
  Phone: 'شماره اړيکه',
  Type: 'ډول',
  Date: 'نېټه',
  Status: 'حالت',
  zone: 'قريه',
  'Tazkira Number': 'تذکره شمېره',
  'Tazkira Type': 'تذکره ډول',
  'Job Title': 'بست عنوان',
  Salary: 'معاش',
  Job: 'وظيفه',
  Absences: 'غير حاضر',
  'Necessary Leave': 'ضروري رخصتي',
  'Sick Leave': 'مريضي رخصتي',
  'Recreational Leave': 'تفريحي رخصتي',
  'General Holidays': 'عمومي رخصتي',
  'G Holidays': 'ع رخصتي',
  Total: 'ټول',
  Present: 'حاضر',

  'Report Date': 'د ګزارش نېټه',
  Search: 'لټون ...',
  Fridays: 'جمعه',
  'Minimum value is ': 'لږ تر لږه شمېره ده ',
  'Maximum value is ': 'لوی تر لویه شمېره ده ',
  'This feild is required': 'دا سيمه ضروري ده',
  'Satanman Arshad': 'ساتنمن ارشد',
  Education: 'زده کړه',
  Educational: 'زده کړي',
  Regional: 'سيمه ايز',
  'Right to Risk': 'د خطر حق',
  'Special Force': 'ځانګړي قطعات',
  cadre: 'کدري',
  'Right to Risk Points': 'د خطر حق امتيازونه',
  'Especial Force Points': 'د ځانګړي قطعاتو امتيازونه',
  'Cadre Points': 'د کدري امتيازونه',
  'Mine Clearance Points': 'د ماين پاکي امتيازونه',
  'Medical Especialist Points': 'د طبي تخصصي امتيازونه',
  'Assign Points': 'امتيازونه ورکول',
  Year: 'کال',
  Month: 'مياشت',
  Filter: 'چاڼګر',
  Remarks: 'تبصرې',
  Report: 'ګزارش',

  Waiting: 'انتظار کې',
  Accepted: 'منل شوی',
  Rejected: 'رد شوی',
  Points: 'امتيازونه',
  Confirm: 'تاييد',
  Reject: 'ردول',
  Cancel: 'لغوه کول',
  Reason: 'سبب',
  Checking: 'بررسي ',
  Approving: 'تصديق کول',
  'Assign Points': 'امتيازونه اضافه کول',
  State: 'حالت',
  Draft: 'مسوده',
  Approved: 'تاييد شوی',
  'Not Verified': 'تاييد نه شوی',
  'Approve Report': 'ګزارش تاييد کول',
  'Are you sure?': 'آيا ډاډه ياست؟',
  "You won't be able to revert this!": 'تاسو نشئ ترته برگرځولی!',
  'Yes, delete it!': 'هو، ړنګول',
  "'Deleted!', 'Your file has been deleted.'": "'ړنګ شو!', 'ستاسو دوتنه ړنګ شوه'",
  Close: 'تړل',
  Provincail: 'ولايتي',
  'Yes, do it!': 'هو، کړه!',
  'Done !': 'ترسره شو !',
  'Your job has been done.': 'ستاسو کار ترسره شو.',
  OK: 'تاييد',
  'Reject Report': 'ګزارش رد کول',
  'Birth Year': 'د زېږون کال',
  'Only English characters are allowed': 'يوازې انګليسي حروف اجازه لري',
  'Employee Information': 'د کارمند مالومات',
  Reset: 'بيا پرځای کول',
  'Create M41 Report': 'د M41 ګزارش جوړول',
  'Create Monotheism Report': 'د توحيد ګزارش جوړول',
  'Month Salary': 'د مياشتې معاش',
  Transport: 'ترانسپورت',
  Retirment: 'تقاعد',
  'Total Points': 'د ټولو امتيازونو',
  Finance: 'ماليه',
  Financail: 'مالي',
  'Total Deduction': 'د ټولو کسرونو',
  'Payable Amount': 'د پرداخت وړ مقدار',
  Macol: 'ماکول',
  bilmaqta: 'بلمقطع',
  Creater: 'جوړونکی',
  Manager: 'مدير',
  'Manager or Commander': 'آمر يا مدير',
  Director: 'رييس يا قوماندان',
  'Send Report': 'ګزارش لېږل',
  Sent: 'لېږل شوی',
  'Receive Report': 'ګزارش ترلاسه کول',
  'Received Report': 'ترلاسه شوی ګزارش',
  'Sent Report': 'تحويل شوی ګزارش',
  Sign: 'امضا',
  Pendding: 'انتظار کې',
  'M41 Is Created': 'M41 جوړ شوی',
  'I Rejected': 'زه رد کړم',
  'Rejected Reason': 'د رد شوي ګزارش سبب',
  'Rejected By': 'رد کونکی',
  Approver: 'تصديق کونکی',
  'Approver Chief': ' د تصديق کونکي رييس',
  'Approved By': 'تاييد کونکی',
  'Monotheism report is created': 'د توحيد ګزارش جوړ شوی',
  Counter: 'محاسب',
  'General Manager': 'مدير عمومي',
  'Soldier/Officer': 'سرباز/افسر',
  Soldier: 'سرباز ',
  Officer: ' افسر',
  Count: 'شمېر',
  Ajer: 'اجير',
  Mamor: 'مامور',
  'Mamor or Ajer': 'مامور يا اجير',
  'Salary General Manager': 'د معاشاتو مدير عمومي',
  'Counter and Salary Assistant': 'د محاسب او معاشاتو معاون',
  'Second Type': 'دوهم ډول',
  'Create m16 Report': 'د M16 ګزارش جوړول',
  'New Item': 'نوی توکي',
  Code: 'کود',
  'Name Da': 'دري نوم',
  'Name En': 'انګليسي نوم',
  'Description Da': 'دري توضيحات',
  'Description En': 'انګليسي توضيحات',
  Description: 'توضيحات',
  'Add Holidays': 'رخصتي اضافه کول',
  Attachment: 'ضمايم',
  'Employee Amount': 'د کارمندانو شمېر',
  'M41 ID': 'د M41 اي ډي',
  'Commit Number': 'د مکلفيت شمېره',
  'Place Code': 'د ځای کود',
  'Payment Method': 'د پرداخت ډول',
  'Budget Type': 'د بوديجه ډول',
  Budget: 'بوديجه',
  'Usage Type': 'د کارولو ډول',
  'Payment way': 'د پرداخت څېره',
  'Organization Code': 'د تشکيل کود',
  'Project Code': 'د پروژې کود',
  'Activity Code': 'د فعاليت کود',
  'Fund Code': 'د وجه کود',
  'District Code': 'د ولسوالۍ کود',

  'Category Code': 'د کټګورۍ کود',
  'Object Code': 'د تصنيف کود',
  'Financial Year': 'د مالي کال',
  'General Chief of Finance': 'د مالي او بوديجې عمومي رييس',
  'M16 report is created': 'د M16 ګزارش جوړ شوی',
  Language: 'ژبه',
}
